hashivim/vim-terraform

- indent/terraform.vim
Thanks for your awesome vim script.
I tried to indent .tf files and I was a little unsatisfied about how it (doesn't correctly) indents terraform blocks.
For example if you had
```
block {
sub_block1 {
}
sub_block2 {
}
}
```
and fixed the whole file's indentation in vim (using = ), sub_block2 would not be properly aligned:
```
block {
sub_block1 {
}
sub_block2 {  // this is wrong
}
}
```
This patch is a modest attempt to fix this (it doesn't for example properly handle /**/ style comments).
Please let me know if you agree with it.
> fixed: block indenting now works properly

- syntax/terraform.vim
This fixes incorrect match on "resource_pool", found in terraform-vsphere provider
> Add word boundaries on "resource", "provider"

- ftdetect/terraform.vim
- syntax/terraform.vim
I wrote this a while back when you weren't maintaining vim-terraform.  Glad to see you're back.
Part of this PR effectively duplicates #6 (still open), since I fixed the ftdetect as well.  However, the nested quotes and function highlighting (and the // comment highlight) are the important parts.
I also removed the resource highlighting completely from my fork (too hard to keep up with), but that's a more opinionated and breaking change so I held it out of this PR.
Original commit message
---
Quoting wouldn't handle backslashed quotes (\") for nesting.  Added
that, and the rarer case of \\" which I found in a function call where I
was attempting to get a literal \" provided to a template.
Also added a rough hack to highlight functions such as split() or join()
differently than variables …
> Syntax highlighting fixes for quoting and functions

- after/ftplugin/terraform.vim
Use the vim tabularize plugin to align declaractions on `=`
You can turn off this behaviour by setting `let g:terraform_align = 0` in your vimrc
> Add functionality to auto-tabularize terraform configurations

- plugin/terraform.vim
It messes with the information when run from vim in a terminal.
> Remove color output.

- syntax/terraform.vim
This PR adds syntax highlighting for `aws_alb`
* https://github.com/hashicorp/terraform/issues/8420
> adding aws_alb

- syntax/terraform.vim
Functions like `base64encode` contain characters other than the alphabet. This change captures that fact.
> Match all alphanumeric function names

- indent/terraform.vim
Indent function argument newline continuation.
This makes it easy to follow when using several interpolations
```hcl
resource "foo_bar" "baz" {
count = "${
length(
var.azs,
)
}"
```
> Indent function argument newline continuation

- syntax/terraform.vim
This pull request adds support for recognizing heredocs.
According to the docs here doc is:
> Multiline strings can use shell-style "here doc" syntax, with the string starting with a marker like <<EOF and then the string ending with EOF on a line of its own. The lines of the string and the end marker must not be indented.
```hcl
resource "aws_instance" "web" {
provisioner "local-exec" {
command = <<CMD
echo ${aws_instance.web.private_ip} >> private_ips.txt && \
echo some other command
CMD
}
}
```
This fixes #25.
> Add heredoc support

- after/ftplugin/terraform.vim
Per the README, spacebar remapping should be disabled by default, but it's not. You can see that spacebar remapping is currently enabled by default by checking your spacebar mappings with `:map` before and after installing this plugin.
> Set spacebar remapping off by default, per README

- .gitignore
- .travis.yml
- Makefile
- test/syntax.vader
This uses https://github.com/junegunn/vader.vim for the unit tests, and
the Travis config is based off
https://github.com/junegunn/seoul256.vim/blob/1475b7610663c68aa90b6e565997c8792ce0d222/.travis.yml
(linked from the vader.vim docs). I can't set up Travis for a repo I don't own
(can I?) so we'll have to see if this works there once it builds.
And to make it all easy to run locally include the relevant set up in a
Makefile. `make check` should run the tests.
Closes #42
> Add automated unit tests of syntax

- README.md
- syntax/terraform.vim
Following #58 that I closed myself I have run the `update_automagic.sh` script for v0.11.3.
NB: The script requires GNU sed. BSD sed, provided on OSX, doesn't support the `I` flag.
> Support for terraform v0.11.3

- README.md
- after/ftplugin/terraform.vim
- override the Vim's default `/*%s*/` commentstring with `#%s`
- add new plugin option `g:terraform_commentstring` to customize it
- update the README.md
> add commentstring option

- ftplugin/terraform.vim
This PR fixes the situation below:
1. open vim without argument(file)
2. open file with `:e main.tf`
3. couldn't load vim-terraform autocmd like `:TerraformFmt` command because on this time already `VimEnter`ed and no events match.
> Change autocmd event from VimEnter to BufEnter

- syntax/terraform.vim
Terraform allows hyphens in identifiers. Consider the following template:
```
data "template_file" "storage-provisioner" {
template = "${file("foo")}"
vars {
provisioner-name = "bar"
}
}
```
Without this change, Vim will highlight the "provisioner" portion of "provisioner-name" as a keyword, different from the remaining "-name" portion.
A side effect is that navigating with "w" will no longer stop at a mid-word hyphen.
> Include hyphens as keyword characters

- syntax/terraform.vim
The [hcl library's scanner](https://github.com/hashicorp/hcl/blob/master/hcl/scanner/scanner.go#L393) allows heredoc labels to be prefixed with a hyphen to indicate that the contents are indented. Furthermore, it allows heredoc labels to include numerals and lowercase letters. Finally, hcl allows the terminal heredoc label to be indented.
Fixes #62
> Align heredoc highlighting with hcl scanner syntax

- ftplugin/terraform.vim
This ensures that code does not get formatted when a textwidth is
set.
> ftplugin: Add set formatoptions-=t

- ftplugin/terraform.vim
Fixes: #84
Terraform v0.12-beta1 now checks file extensions for `terraform fmt`.
https://github.com/hashicorp/terraform/pull/20040
So we must specify the temporary file extension.
> Add .tf extension to a temporary file for `terraform fmt`

- ftplugin/terraform.vim
Fixes [this issue](https://github.com/tpope/vim-fugitive/issues/1128) related with vim-fugitive buffers from the vim-terraform side.
> Prevent terraform fmt autosave from attempting to write to a target which isn't filereadable

- syntax/terraform.vim
Hi folks,
As you may know, Terraform v0.12, next major release, will introduce new configuration language HCL2.
It would be great if we could support HCL2 and Terraform v0.12.
https://www.hashicorp.com/blog/terraform-0-1-2-preview
I added simple HCL2 syntax highlight to my nvim, and I'm using it with Terraform v0.12-beta1.
I'm testing it with nvim v0.3.2.
I know that the current implementation is probably not perfect but not so bad.
So I will share this to all.
I believe this will give us a good start point for support HCL2 and Terraform v0.12.
The complete language specification of HCL2 is as follows:
https://github.com/hashicorp/hcl2/blob/master/hcl/hclsyntax/spec.md
Upgrade guide to Terraform v0.12 is here:
https://www.terraform.io/upgrade-guides/0-12.html
Note:
For now, it doesn't …
> Add support for simple HCL2 / Terraform v0.12 syntax highlight

- indent/terraform.vim
In particular, we now recognize lines beginning with '#' as comments.
Fixes #53.
(We can still be fooled by multiilne /* ... */ style comments.  Too
bad).
> Simplify and improve indent

- syntax/terraform.vim
As alternative approach to folding - more succinct than the `TerraformFolds()` and capable of folding inner blocks, but perhaps not really any better.
Still I think it makes sense for the syntax to understand this; after all no-one has to use `foldmethod=syntax` if they don't want to.
> Enable folding with foldmethod=syntax

- README.md
- ftplugin/terraform.vim
Just use the right value always
I expect this to be the least controversial part of the slimming program proposed in #94.
No rush to merge this - indeed we should probably leave it open for a little while so that users have at least some opportunity to notice and object.
> Remove g:terraform_commentstring

- autoload/terraform.vim
- ftplugin/terraform.vim
Another part of the general simplification proposed in #94.
Syntax-based folding does behave slightly differently than the expression-based folding that I'm removing here - though I think mostly better, as in it allows more folds (if you want them).  And the automatic fold expression is not quite the same as the one that we were previously providing.
However the simplification of the plugin - this pull request mostly just removes a pile of code - is IMO enough to justify such small changes.
As with the other pull requests in this series, no rush to merge - indeed it would probably be polite to leave this open for a short while so that users have a chance to notice and object.
> Use syntax-based folding

- README.md
- syntax/terraform.vim
- update_automagic.sh
- update_commands.rb
`update_automagic.sh` no longer needs you to have the most up to date terraform on your PATH.
`update_commands.rb` now searchs for a local terraform before searching the PATH.
> Ran the updater against TF 0.12.8. Updated the list of resources, datasources, and providers.

- autoload/terraform.vim
If TF_CLI_ARGS or TF_CLI_ARGS_fmt env vars are used formatting may fail with invalid args. For example, `TF_CLI_ARGS_fmt=<tf_dir>` may be desirable for running outside of vim, but when vim-terraform adds thcalls `terraform fmt <tf_dir>` will cause it to fail due to twice listing the directory when only a single argument is expected.
This commit addresses the issue by ensuring no args come from the environment when vim-terraform calls fmt.
> Fix #114: fmt error if TF_CLI_ARGS* in env

- autoload/terraform.vim
- ftplugin/terraform.vim
- update_commands.rb
Broken by the switch to using `customlist` for completion.  Change back!
> Fix autocompletion for partial Terraform arguments

- syntax/terraform.vim
Otherwise, the string following the `data` keyword (the data type) gets
highlighted as a string rather than as a `terraDataTypeBI`
Before:
After:
> Remove data from keywords

- syntax/terraform.vim
prefer "syn keyword" over "syn match", and remove a couple of unintended
duplications
> Syntax tweaks

- syntax/terraform.vim
- test/syntax.vader
Attempt to improve the treatment of interpolated strings, and functions:
- un-highlight the terraStringInterp region, and un-restrict the things
that it can contain
- don't treat terraValueFunction as a region, just highlight the
function name
The intention is that things inside interpolated strings, and arguments
to functions, just get their regular highlighting
> Tweak syntax highlighting

- syntax/terraform.vim
Fixes #112 - except possibly for "some related cases" which that issue
mentions but does not specify.
> Skip escaped backslashes in strings

- ftdetect/terraform.vim
See #133.  I'm not fully convinced that this should be necessary, but it
certainly ought to be harmless.
> Silence any errors clearing TinyFugue association

- get_providers.sh
On OSX, not having a path argument results in an error with the use of `-not`.
```
$ find . -type f -not -name "*provider*" 1>/dev/null
$ find -type f -not -name "*provider*" 1>/dev/null
find: illegal option -- t
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
```
```
Updating files: 100% (2597/2597), done.
find: illegal option -- t
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
Cloning into 'terraform-provider-acme'...
```
> Fix illegal option error in find

- autoload/terraform.vim
I _think_ this is unnecessary, and it should fix #138.
> Drop the filereadable check before formatting

- syntax/terraform.vim
Eg `base64encode()` should now highlight correctly.
So far as I can see, digits and lowercase letters are sufficient, so
also remove the TODO.
> Allow digits in function names

- autoload/terraform.vim
Sometimes - eg when TF_LOG is set - terraform writes both stdout and
stderr.  Redirect stderr to a temporary file, show it if there was a
problem.
> Capture stderr in its own file, when formatting

- indent/terraform.vim
This PR fixes indentation for block comments.
Previously, when typing out a block comment, you'd get this:
```
/*
*
*/
foo
/*
*
*/
foo # note that this line is too indented
```
instead of this:
```
/*
*
*/
foo
```
> Fix indentation for block comments

- indent/terraform.vim
I've for a long time been dealing with issues when using heredocs and
tabs.  Today I notice that it too inserted tabs when creating newlines
inside a resource.  Have never really been bothers by it as these got
changed to spaces after running `terraform fmt`.  However, as said, I
noticed that this occurred more places and needed to look for a fix.
By explicitly setting `expandtab`, we make sure that Vim uses spaces
instead of tabs when we press enter to insert a newline.
---
I find it strange that no one else has had this issue?  I did disable all of my plugins to make sure that I did not interfere.
> fix: set expandtab so that newlines respect indent

- README.md
A little PR to add 3 classic vim package managers: Vim-plug, Packer and Lazy.  
The arguments for Lazy.nvim allow lazy-loading, meaning the plugin will only be loaded on Terraform files or when the commands are used.
> Add Vim-plug/Packer/Lazy install instructions

- README.md
- ftdetect/hcl.vim
Adds filetype detection for `*.tfbackend` files as described here: https://developer.hashicorp.com/terraform/language/settings/backends/configuration#file
> Add filetype detection for `*.tfbackend` files

- ftplugin/terraform.vim
Hi, I added file format for testing framework to `terraform_fmt_on_save`.
ref. https://github.com/hashicorp/terraform/pull/33576
> add: enabled format for `*.tftest.hcl` files

- syntax/hcl.vim
As titled. While I realize that this is similar to #185 which was closed, I believe that just adding the underscore will keep the regex idiomatic while covering common, real-world cases.
The HCL spec here: 
https://github.com/hashicorp/hcl/blob/main/hclsyntax/spec.md#identifiers
contains the following paragraph:
> The dash character `-` is additionally allowed in identifiers, even though
that is not part of the unicode `ID_Continue` definition. This is to allow
attribute names and block type names to contain dashes, although underscores
as word separators are considered the idiomatic usage.
I believe this sufficiently implies that the use of `_` as an idiomatic word-separator character in identifiers.
Additionally, we can see real-world adoption of this practice in projects like …
> add underscore to HCL function identifier regex

- ftdetect/hcl.vim
OpenTofu 1.8 adds support for [`.tofu` files](https://opentofu.org/docs/intro/whats-new/#override-files-for-opentofu-keeping-compatibility) which override `.tf` files of the same name. The syntax is still the same, so we can apply the usual `terraform` filetype configuration to these files as well.
> Add .tofu and .tofutest.hcl to list of extensions
