hashivim/vim-terraform

syntax/terraform.vim
=> Add provisioner and module syntax

syntax/terraform.vim, update_data_sources.rb
* adding update_data_sources.rb to parse for data sources 
* adding syntax highlighting for data like resource 
* adding comments in syntax/terraform.vim to anchor on
Pulled latest source for Terraform to update from, not sure if you pull a tag to keep in sync?
=> Add highlighting for data sources

plugin/terraform.vim, syntax/terraform.vim
Thanks for the ruby scripts team! They made this super simple.
=> Feature/update syntax for terraform 0.8.2/pgporada

README.md, after/ftplugin/terraform.vim
Resolves https://github.com/hashivim/vim-terraform/issues/21
=> Allow indentation override to match :TerraformFmt

README.md, syntax/terraform.vim, update_automagic.sh
Instead of running 3 ruby scripts, it's easier to run 1 bash script that runs 3 ruby scripts!
```
$ ./update_automagic.sh 0.8.7
+) Acquiring terraform-0.8.7
--2017-02-27 17:31:33--  https://github.com/hashicorp/terraform/archive/v0.8.7.tar.gz
Resolving github.com (github.com)... 192.30.253.113, 192.30.253.112
Connecting to github.com (github.com)|192.30.253.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/hashicorp/terraform/tar.gz/v0.8.7 [following]
--2017-02-27 17:31:33--  https://codeload.github.com/hashicorp/terraform/tar.gz/v0.8.7
Resolving codeload.github.com (codeload.github.com)... 192.30.253.121, 192.30.253.120
Connecting to codeload.github.com (codeload.github.com)|192.30.253.121|:443... connected.
HTTP request sent, …
```
=> Feature/run helper scripts for terraform 087/pgp

syntax/terraform.vim
Resource was recently added: https://github.com/hashicorp/terraform/pull/13098
=> Add keyword: aws_ses_domain_identity

after/ftplugin/terraform.vim
+ Added code to allow for folding sections of terraform configuration
Code copied directly from https://github.com/jgerry/terraform-vim-folding `foldlevel` altered from 0 to 1
=> Add ability to fold sections

after/ftplugin/terraform.vim
This allows the data and terraform sections to be folded as well
=> Add data and terraform folding sections

syntax/terraform.vim
Closes #14, #28 
Given the notice about "maintainer wanted" I am ware that opening this PR runs
the risk of me being given maintainer status, and I guess I'm okay with that.
Before:
After:
=> Fix syntax highlighting for user-map variables

README.md, after/ftplugin/terraform.vim
=> Allow disabling the spacebar remap

syntax/terraform.vim, test/syntax.vader
=> String interpolation can containt other interpolations too.

.travis.yml, Makefile, README.md, test/syntax.vader, test/terraform_align.vader, test/terraform_remap_spacebar.vader
The makefile now resembles other that I've written and ran for projects. Added tests for the terraform_remap_spacebar function. The tests now cleanup after themselves so they do not interfere with other test files.
=> Makefile and tests upgrade

.gitignore, .travis.yml, Makefile, README.md, after/ftplugin/terraform.vim, get_providers.sh, plugin/terraform.vim, syntax/terraform.vim, test/syntax.vader, test/terraform_align.vader, test/terraform_remap_spacebar.vader, update_automagic.sh, update_data_sources.rb, update_provider_syntax.sh, update_syntax.rb
WIP, do not merge yet.
This fixes #40.
=> Update provider syntax for newest version of Terraform

syntax/terraform.vim
Simple PR that enables `locals` block highlighting.
=> Add locals block highlighting

ftdetect/terraform.vim
Change tfstate filetype from javascript to json.
=> change filetype on tfstate files to json

autoload/terraform.vim, ftplugin/terraform.vim, syntax/terraform.vim, test/terraform_align.vader, test/terraform_remap_spacebar.vader, update_commands.rb
I seem to have misplaced a line or two at some point during earlier refactoring.
=> Fix the cpoptions dance

autoload/terraform.vim
Avoid the temporary file.
Fixes #64
=> Rewrite terraform#fmt

README.md
And reduce header size to be more readable
=> Add installation instruction for Vim 8 packages

syntax/terraform.vim
- Remove unused terraValueVarSubscript
- Remove terraCommentGroup, a cluster containing exactly one thing
hardly seems worthwhile
=> Tidying the syntax

README.md, get_providers.sh, syntax/terraform.vim, update_data_sources.rb, update_resources.rb
Azurerm resources need to be investigated.
=> Updated for terraform 0.12.20

README.md, autoload/terraform.vim, ftplugin/terraform.vim
First time doing vimscript ^^
It seems to work.
My use case is the following : For some projects I have to use TF 0.10.8 but the fmt is messy and I prefer using the latest fmt version.
=> Add support for custom terraform binary path

doc/terraform.txt
=> Expand native vim documentation

syntax/hcl.vim
=> sync ccomment
